### ISSUE TITLE
port to qtwebengine needed

### ISSUE THREAD

**Issue by t0b3** [sparqlunicorn/sparqlunicornGoesGIS#33]
because qtwebkit is being phased out and not present on my system I get the error message

**ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'**
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/__init__.py", line 35, in classFactory
    from .sparql_unicorn import SPARQLunicorn
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/sparql_unicorn.py", line 49, in 
    from .dialogs.loginwindowdialog import LoginWindowDialog
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/dialogs/loginwindowdialog.py", line 3, in 
    from PyQt5.QtWebKitWidgets import QWebView
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```
thus https://github.com/sparqlunicorn/sparqlunicornGoesGIS/blob/c43de9e8c4c14cff59fe8a321137b76ef6338499/dialogs/loginwindowdialog.py#L3 needs to be ported to `PyQt5.QtWebEngineWidgets` and `QWebEngineView`

**Comment by situx** [comment]
Hi! Thank you for noticing. I will add a fix to the next release!
