### ISSUE TITLE
Check if required dependencies (libs) are installed

### ISSUE THREAD

**Issue by sfkeller** [sparqlunicorn/sparqlunicornGoesGIS#4]
When this plugin is being installed from within QGIS and the required dependencies (libs) are _NOT_ installed, I got the following error.

So there could be a check, if required dependencies (libs) are installed?

````
Couldn't load plugin 'sparqlunicorn' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'SPARQLWrapper' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/sfkeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\sparqlunicorn\__init__.py", line 35, in classFactory
    from .sparql_unicorn import SPAQLunicorn
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/sfkeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\sparqlunicorn\sparql_unicorn.py", line 42, in 
    from SPARQLWrapper import SPARQLWrapper, JSON
  File "C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python\qgis\utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'SPARQLWrapper'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.2-Zanzibar Zanzibar, 4470baa1a3 

Python Path:
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python
C:/Users/sfkeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/sfkeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.8/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.8\bin\python37.zip
C:\PROGRA~1\QGIS3~1.8\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib
C:\Program Files\QGIS 3.8\bin
C:\PROGRA~1\QGIS3~1.8\apps\Python37
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.8\apps\Python37\lib\site-packages\Pythonwin
C:/Users/sfkeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\sfkeller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
````

**Comment by situx** [comment]
We included all our dependencies in the plugin package from version 0.10 onwards. Therefore this issue will be closed
