### ISSUE TITLE
Install failing on QGis 3.34.10-Prizren

### ISSUE THREAD

**Issue by ldesousa** [sparqlunicorn/sparqlunicornGoesGIS#40]
Running QGis 3.34.10-Prizren on Ubuntu 24.04, installed with Nix to the user profile. The plug-in fails to install as it cannot find a Python library. The full log is below.

```
Couldn't load plugin 'sparqlunicorn' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pyparsing' 
Traceback (most recent call last):
  File "/nix/store/vhgv7927q9fkl8m7ls57fxndcrh343j2-qgis-ltr-unwrapped-3.34.10/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lads/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/__init__.py", line 35, in classFactory
    from .sparql_unicorn import SPARQLunicorn
  File "/nix/store/vhgv7927q9fkl8m7ls57fxndcrh343j2-qgis-ltr-unwrapped-3.34.10/share/qgis/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lads/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/sparql_unicorn.py", line 51, in 
    from .dialogs.sparql_unicorn_dialog import SPARQLunicornDialog
  File "/nix/store/vhgv7927q9fkl8m7ls57fxndcrh343j2-qgis-ltr-unwrapped-3.34.10/share/qgis/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lads/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/dialogs/sparql_unicorn_dialog.py", line 36, in 
    from rdflib.plugins.sparql import prepareQuery
  File "/nix/store/vhgv7927q9fkl8m7ls57fxndcrh343j2-qgis-ltr-unwrapped-3.34.10/share/qgis/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lads/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/dependencies/rdflib/plugins/sparql/__init__.py", line 36, in 
    from . import operators, parser, parserutils  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vhgv7927q9fkl8m7ls57fxndcrh343j2-qgis-ltr-unwrapped-3.34.10/share/qgis/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lads/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/dependencies/rdflib/plugins/sparql/operators.py", line 25, in 
    from pyparsing import ParseResults
  File "/nix/store/vhgv7927q9fkl8m7ls57fxndcrh343j2-qgis-ltr-unwrapped-3.34.10/share/qgis/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyparsing'


Python version: 3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.3.0] 
QGIS version: 3.34.10-Prizren Prizren, exported 

Python Path:
/home/lads/.local/share/QGIS/QGIS3/profiles/default/python/plugins/sparqlunicorn/dependencies
/nix/store/vhgv7927q9fkl8m7ls57fxndcrh343j2-qgis-ltr-unwrapped-3.34.10/share/qgis/python
/home/lads/.local/share/QGIS/QGIS3/profiles/default/python
/home/lads/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/nix/store/vhgv7927q9fkl8m7ls57fxndcrh343j2-qgis-ltr-unwrapped-3.34.10/share/qgis/python/plugins
/nix/store/wpwzq3fp5vwvv6qxw9vyhi6l0k0p6bkq-python3.11-chardet-5.2.0/lib/python3.11/site-packages
/nix/store/kd46nissmv5wd0wigm27kwrnmc452yd1-gdal-3.9.2/lib/python3.11/site-packages
/nix/store/qigqbnrzsyd67bi1clk25b6zdj9b9dfp-python3.11-jinja2-3.1.4/lib/python3.11/site-packages
/nix/store/bwjg11hqf0x0xirq9iwzvc77qsm77333-python3.11-markupsafe-2.1.5/lib/python3.11/site-packages
/nix/store/l3wfljsrn4jna6xzajwm5qvcy1lc916l-python3.11-numpy-1.26.4/lib/python3.11/site-packages
/nix/store/fsyi36hwzcwjv2q8lvwnax0jhydnwhap-python3.11-owslib-0.31.0/lib/python3.11/site-packages
/nix/store/8andb5ylljdvp18sbf9d0zxb1m2av6ff-python3.11-lxml-5.2.2/lib/python3.11/site-packages
/nix/store/q5ggq0d4f4fblhsdqlzgfmjm8fnj89pg-python3.11-pyproj-3.6.1/lib/python3.11/site-packages
/nix/store/j3x3r55ypbcpbi25w9h4gxfq3k8nifi7-python3.11-certifi-2024.07.04/lib/python3.11/site-packages
/nix/store/glxgnbigqawysr06plhm1spm8w204yc2-python3.11-python-dateutil-2.9.0.post0/lib/python3.11/site-packages
/nix/store/dcfbpn7q6wiq97far5fc810d6xfnb0bd-python3.11-six-1.16.0/lib/python3.11/site-packages
/nix/store/630lsf4rp6yn79j76c7yl9dfw0dg66ks-python3.11-pytz-2024.1/lib/python3.11/site-packages
/nix/store/nz6fq9nlshdsq91rbf8xnabw2pl1n2xl-python3.11-pyyaml-6.0.2/lib/python3.11/site-packages
/nix/store/m1pxgz7388a7kgj7pvzg3ggs0nb4hckj-python3.11-requests-2.32.3/lib/python3.11/site-packages
/nix/store/vknd5lybq4ijn0xnfgx6w6a73ar2dy5a-python3.11-brotlicffi-1.1.0.0/lib/python3.11/site-packages
/nix/store/8w6m4kb86gbdp8k6yj3z44nx181h1qyx-python3.11-cffi-1.17.0/lib/python3.11/site-packages
/nix/store/4v0yhm5v42g8h0b8pmipmhjba6ncyp0y-python3.11-pycparser-2.22/lib/python3.11/site-packages
/nix/store/clib4lm3jf7c40jyrrg1hpzkzgdsdsci-python3.11-charset-normalizer-3.3.2/lib/python3.11/site-packages
/nix/store/i6cwb82mdw5drg0yygp44204b4ilppxj-python3.11-idna-3.7/lib/python3.11/site-packages
/nix/store/gryljhqc68lkd6nbcmaw7zj76zhzyik0-python3.11-urllib3-2.2.2/lib/python3.11/site-packages
/nix/store/2i405452ii9g7ixcax72zar2181fzh5b-python3.11-psycopg2-2.9.9/lib/python3.11/site-packages
/nix/store/mxl81f2pvndz1c70y7jmwd9vzx2kfkn7-python3.11-pygments-2.18.0/lib/python3.11/site-packages
/nix/store/plisj2ikm1bhpr1x96vb15rii6h8v8rc-python3.11-pyqt5-5.15.10/lib/python3.11/site-packages
/nix/store/9hv4h6mq477m3cz4danf2w51gicw5rcy-python3.11-pyqt-builder-1.16.2/lib/python3.11/site-packages
/nix/store/gcblczsrc670d18aars6701pv7q81ac6-python3.11-packaging-24.1/lib/python3.11/site-packages
/nix/store/qnf9kzk2c9r4sf3bwzh8z7ydjhkq25qh-python3.11-sip-6.8.3/lib/python3.11/site-packages
/nix/store/ngr4rppv9z17dzr8zp25jvyicdkcpcnv-python3.11-setuptools-72.1.0/lib/python3.11/site-packages
/nix/store/d3y2dqa063p95y4hfdhq6pq56av9m9jr-python3.11-qscintilla-qt5-2.13.2/lib/python3.11/site-packages
/nix/store/cn3g15wwqzqsxgbaic5772rsfg7j1pkm-python3.11-dbus-python-1.3.2/lib/python3.11/site-packages
/nix/store/x233k9ij7c2llc06i0h2fvyrqp3hpbfs-python3.11-pyqt5-sip-12.13.0/lib/python3.11/site-packages
/nix/store/zy22nlap6gznpjhqry4w0hgw5mf62q3f-python3-3.11.9/lib/python311.zip
/nix/store/zy22nlap6gznpjhqry4w0hgw5mf62q3f-python3-3.11.9/lib/python3.11
/nix/store/zy22nlap6gznpjhqry4w0hgw5mf62q3f-python3-3.11.9/lib/python3.11/lib-dynload
/nix/store/zy22nlap6gznpjhqry4w0hgw5mf62q3f-python3-3.11.9/lib/python3.11/site-packages
/home/lads/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by ldesousa** [comment]
This looks an issue with dependencies in Nix. I will leave this issue open an report back once I get more details.
